### ISSUE TITLE
CollapseCodegenStages in QueryStage will use withNewChildren to replace the original SparkPlan 

### ISSUE THREAD

**Issue by windpiger** [Intel-bigdata/spark-adaptive#68]
CollapseCodegenStages in QueryStage will use withNewChildren to replace the original SparkPlan , the new sparkplan will lose some info, such as sideEffectResult in DataWritingCommandExec.

for example:
```
spark.sql("create table test_tbl as select xxxx")
spark.collect

exception:
test_tbl already exists.
```

spark.sql  already execute querystage, and already compute lazy variable sideEffectResult in DataWritingCommandExec.
while when  execute collect, it will execute CollapseCodegenStages in QueryStage again,
and DataWritingCommandExec is replaced by withNewChildren in CollapseCodegenStages, so 
sideEffectResult of the new DataWritingCommandExec is null ,it will be init again, and this time it will 
cause test_tbl already exists.

**Comment by carsonwang** [comment]
Fixed by #70
