### ISSUE TITLE
Spark SQL UI  history  can not catch the  sparkplan graph of AE  after  closing  sparkSQL Cli 

### ISSUE THREAD

**Issue by southernriver** [Intel-bigdata/spark-adaptive#72]
The  running status for spark plan graph:
![image](https://user-images.githubusercontent.com/20614350/49417844-709b3e00-f7ba-11e8-9a20-a5849ddc18fa.png)

after closing  SparkSQL Cli and open the history server:
![image](https://user-images.githubusercontent.com/20614350/49417847-78f37900-f7ba-11e8-8b60-94d836b1b925.png)

**Comment by carsonwang** [comment]
I believe this is your modified AE version as we don't have coordinator id in the Exchange. Let me know if you can reproduce the issue using our latest branch. If so please paste the new images here.

**Comment by yucai** [comment]
@southernriver @carsonwang I think that history server is the upstream/internal version, which has no AE patches, actually, we need some special UI support for the AE's operator.
Just start the history server from AE version's Spark, it should work.

**Comment by southernriver** [comment]
@carsonwang  yes, I did update something  for  AE. But  the  latest AE version  also leads  to the same result.
![image](https://user-images.githubusercontent.com/20614350/49424014-40609900-f7d4-11e8-901f-881531e64ad8.png)
![image](https://user-images.githubusercontent.com/20614350/49424019-45254d00-f7d4-11e8-8ea0-b47c7ce8456d.png)

as @yucai   said , I will  start the history server from AE version's Spark, It  should be able to solve this.
thank you all.

**Comment by carsonwang** [comment]
Thanks for update. I'll close this.
