### ISSUE TITLE
Why a sql job OFF AE is better than ON AE ?

### ISSUE THREAD

**Issue by weixiuli** [Intel-bigdata/spark-adaptive#74]
There is a sql job, which OFF AE is better than ON AE?

conf:
  --conf spark.sql.crossJoin.enabled=true \
  --conf spark.dynamicAllocation.enabled=true \
  --conf spark.dynamicAllocation.minExecutors=2 \
  --conf spark.dynamicAllocation.maxExecutors=10000 \
  --conf spark.dynamicAllocation.initialExecutors=2 \
  --conf spark.dynamicAllocation.executorIdleTimeout=20s \
  --conf spark.shuffle.service.enabled=true \
  --conf spark.sql.adaptive.enabled=true \
  --conf spark.sql.adaptive.minNumPostShufflePartitions=1 \
  --conf spark.sql.adaptive.maxNumPostShufflePartitions=2000 \
  --conf spark.sql.adaptive.shuffle.targetPostShuffleInputSize=67108864 \
  --conf spark.sql.adaptive.shuffle.targetPostShuffleRowCount=20000000 \

A sql like that:

``insert` overwrite table ***** partition(ct, dt)
SELECT bs,
         os,
         app_version,
         request_tm,
         online_log.pin,
         coalesce(pin_account.pin_type,
         '**') AS pin_type, pin_account.vender_id, page_title, page_par, refer_page_title, refer_page_par, session_rt, click_id, click_par, os_version, device_brand, device_type, chan_info, ct, dt
FROM 
    (SELECT 'click' AS ct, bs, os, app_version, request_tm, user_log_acct AS pin, regexp_replace(ct_page, '[,@^|]', '') AS page_title, regexp_replace(request_par, '[,@^|]', '') AS page_par, regexp_replace(refer_page, '[,@^|]', '') AS refer_page_title, regexp_replace(refer_par, '[,@^|]', '') AS refer_page_par, NULL AS session_rt, click_id, click_par, os_version, device_brand, device_type, chan_info, dt
    FROM gdm.gdm_m14_unify_online_log_mark
    WHERE dt = '2018-12-16'
            AND bs IN ('jm', 'jmpc')
    UNION
    allSELECT 'browse' AS ct, bs, os, app_version, request_tm, user_log_acct AS pin, regexp_replace(ct_page, '[,@^|]', '') AS page_title, regexp_replace(request_par, '[,@^|]', '') AS page_par, regexp_replace(refer_page, '[,@^|]', '') AS refer_page_title, regexp_replace(refer_par, '[,@^|]', '') AS refer_page_par, session_rt, NULL AS click_id, NULL AS click_par, os_version, device_brand, device_type, chan_info, dt
    FROM gdm.gdm_m14_unify_online_log
    WHERE dt = '2018-12-16'
            AND bs IN ('jm', 'jmpc')
    UNION
    allSELECT 'click_old' AS ct,
        CASE
        WHEN platform LIKE '%pc%' THEN
        'jmpc'
        ELSE 'jm'
        END AS bs, platform AS os,
        CASE
        WHEN operationid IN ('100000', '100002') THEN
        ext_1
        ELSE null
        END app_version, opdate AS request_tm, pin AS pin, NULL AS page_title, NULL AS page_par, NULL AS refer_page_title, NULL AS refer_page_par, NULL AS session_rt, operationid AS click_id, concat(ext_1, '_', ext_2, '_', ext_3) AS click_par, NULL AS os_version, NULL AS device_brand, NULL AS device_type, NULL AS chan_info, to_date(opdate) AS dt
    FROM fdm.fdm_jm_data_statistics_chain
    WHERE dp IN ('ACTIVE')
            AND to_date(opdate) = '2018-12-16' ) AS online_log left join
    (SELECT name AS pin,
         creator AS vender_id,
         'aaa' AS pin_type
    FROM fdm.fdm_popware_vender_login_caccount_chain
    WHERE dp IN ('ACTIVE')
    UNION
    all SELECT name AS pin,
         vender_id,
         'bbb' AS pin_type
    FROM fdm.fdm_pophc_vender_login_account_chain
    WHERE dp IN ('ACTIVE') ) AS pin_account
    ON online_log.pin = pin_account.pin; `

`1. Off AE`
![image](https://user-images.githubusercontent.com/39684231/50333235-ac1a6400-053f-11e9-9db1-246d4b314936.png)
`2.On  AE`
![image](https://user-images.githubusercontent.com/39684231/50333294-e1bf4d00-053f-11e9-8187-8d4331d45269.png)
![image](https://user-images.githubusercontent.com/39684231/50334281-bf7afe80-0542-11e9-95ea-fa45fd77077e.png)

**Comment by gczsjdy** [comment]
AE shouldn't have impact on leaf stages... Have you re-run this for multiple times?

**Comment by weixiuli** [comment]
Yeh,@gczsjdy, i have re-run it and find it sames like above .

![image](https://user-images.githubusercontent.com/39684231/50393600-42de5f00-0792-11e9-96d6-ba5dc15e7c74.png)

![image](https://user-images.githubusercontent.com/39684231/50393636-75885780-0792-11e9-934a-ce665d39b11f.png)

**Comment by gczsjdy** [comment]
@weixiuli They are not corresponding stages? See the data size...
