### ISSUE TITLE
Q23b in TPC-DS will hang when enable ae in 2gb data scale.

### ISSUE THREAD

**Issue by JkSelf** [Intel-bigdata/spark-adaptive#76]
The sql is available in [q23b.sql](https://docs.google.com/document/d/1Y8wyAwevGON024i81Zg3Pp0WPt6jimUR7nrDHUl4ME0/edit) The subquery in q23b is the max_store_sales table. 
The jstack info of Q23b hang is available in [jstack](https://docs.google.com/document/d/19TdXrA6Ao0ttAfoWvmJVqvJwLmuSKpZxJwhED39Chjo/edit?usp=sharing)
From the jstack info, the subquery is always not done and other stage is always waiting the result of subquery.

**Comment by JkSelf** [comment]
![image](https://user-images.githubusercontent.com/11972570/51099069-75b3ca00-1809-11e9-8013-9eea508a584b.png)

Q23b have 3 subquery and the child of all the 3 subquery  are the same(ResultQueryStage). 
A **strange question** is why the  [prepareExecuteStage ](https://github.com/Intel-bigdata/spark-adaptive/blob/011c2d325926808b00beb5329698b640da5e340b/sql/core/src/main/scala/org/apache/spark/sql/execution/adaptive/QueryStage.scala#L95)in above ResultQueryStage is execute 3 times not once.  And we have added `synchronized` and have `prepared `variable to check.

From the log, the same `ResultQueryStage` object call preparedExecuteStage method 3 times and it seems the synchronized does not affect.

The log in code:
![image](https://user-images.githubusercontent.com/11972570/51099404-6e8dbb80-180b-11e9-92cd-254962f290f2.png)

The print log:
`19/01/14 09:50:08 INFO adaptive.ResultQueryStage: The prepared value is false and the prepareExecuteStage method in QueryStage is running and the current thread is subquery-1 and the this class is org.apache.spark.sql.execution.adaptive.ResultQueryStage@9957cce0`
`19/01/14 09:50:08 INFO adaptive.ResultQueryStage: The prepared value is false and the prepareExecuteStage method in QueryStage is running and the current thread is subquery-0 and the this class is org.apache.spark.sql.execution.adaptive.ResultQueryStage@9957cce0`
`19/01/14 09:51:09 INFO adaptive.ResultQueryStage: The prepared value is false and the prepareExecuteStage method in QueryStage is running and the current thread is subquery-2 and the this class is org.apache.spark.sql.execution.adaptive.ResultQueryStage@9957cce0`

**Comment by southernriver** [comment]
@JkSelf  I came across the same problem as you.The status shown in the UI is completed，but the spark-sql client  was waiting. 
<img width="586" alt="image" src="https://user-images.githubusercontent.com/20614350/51474899-bbe5cc00-1dbb-11e9-8bb0-06f191bf18da.png">

The jstack  status was waiting on condition:
<img width="320" alt="image" src="https://user-images.githubusercontent.com/20614350/51475516-82ae5b80-1dbd-11e9-93e9-6dc795f72800.png">

And for the other case, like query06,query14(2),query23(2),query54,query58 will also lead to the same  
issue.

**Comment by JkSelf** [comment]
The above founding is wrong. In fact, the child of all the 3 subquery are not the same.
The root cause is that: the filter operator is synchronized when waiting the result of subquery 
 in [synchronized code](https://github.com/Intel-bigdata/spark-adaptive/blob/61bd1c99bd185cbb6a3e2343cb7bc7354ad89220/sql/core/src/main/scala/org/apache/spark/sql/execution/SparkPlan.scala#L187) and in the QueryStage we need synchronized the above synchronized filter operator when update UI . so the sql is hanged.
 Solutions are as following:
1. Change the synchronized in waitForSubqueries to lock to make the locked object is different;
2.  Disable update UI when the sql contains subquery;
3.  Update UI once only after executed sql

Currently I tend to the solution one, because this method does not affect the function of updating UI. And I will create PR to fix.

**Comment by JkSelf** [comment]
@southernriver I create [PR#80](https://github.com/Intel-bigdata/spark-adaptive/pull/80) to resolve this issue. And you can test whether this patch can resolve your issues. Thanks.

**Comment by JkSelf** [comment]
Fixed in [PR#80](https://github.com/Intel-bigdata/spark-adaptive/pull/80) . So close this issue.
